
args:

  device: cuda
  data_dir: '/home/user/data/a_bearing/a_020_DIRG_pro/' # '/home/user/data/a_bearing/a_006_THU_pro/LQ_fusion/' '/home/user/data/a_bearing/a_018_THU24_pro/'
  dataset_task: DIRG_020_basic # THU_006_basic THU_006_generalization THU_006_fusion THU_018_basic THU_018_generalization THU_018_fusion

  target: '500' # if basic or generalization 1hz 10hz 15hz
  k_shot: 64


# model
  model: 'WKN_m'
  skip_connection: True
  num_classes: 7
  in_dim : 4096
  out_dim : 4096
  in_channels : 6
  out_channels : 3
  scale : 4

  f_c_mu: 0
  f_c_sigma: 0.1
  f_b_mu: 0
  f_b_sigma: 0.1

# hyperparameter
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 300
  weight_decay: 0.0001
  num_workers: 32
  seed: 17

# train
  monitor: 'val_loss'
  patience: 100
  gpus: 1
  weight_decay: 0.0001
  l1_norm: 0.001

  log_parameters: True

  pruning: [0.7,0.5,0.01]
  snr: 1