signal_processing_configs:
  layer1: ['HT','WF','I']
  layer2: ['HT$,'WF','I']
  # layer2: ['$HT$','$WF$','$I$']
  # layer3: ['$HT$','$WF$','$I$']
  # layer4: ['$HT$','$WF$','$I$']   

feature_extractor_configs: ['$Mean$', '$Std$', '$Var$','$Entropy$',
 '$Max$', '$Min$', '$AbsMean$', '$Kurtosis$','$RMS$','$CrestFactor$',
 '$Skewness$','$ClearanceFactor$','$ShapeFactor$']
# logical_configs:
  # channel_1:
  #   features: ['$Mean$', '$Std$']
  # channel_2:
  #   features: ['$Mean$', '$Std$']
args:

  device: cuda
# data



# model
  skip_connection: true
  num_classes: 5
  in_dim : 4096
  out_dim : 4096
  in_channels : 2
  out_channels : 3
  scale : 2

  f_c_mu: 0
  f_c_sigma: 0.1
  f_b_mu: 0
  f_b_sigma: 0.1

# hyperparameter
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 10
  weight_decay: 0.0001
  num_workers: 4
  seed: 17
