signal_processing_configs:
  layer1: ['HT','WF','I']
  layer2: ['HT','WF','I']
  layer3: ['HT','WF','I']
  layer4: ['HT','WF','I']

  # layer1: ['HT','I']
  # layer2: ['HT','I']
  # layer2: ['$HT$','$WF$','$I$']
  # layer3: ['$HT$','$WF$','$I$']
  # layer4: ['$HT$','$WF$','$I$']   

feature_extractor_configs: ['Mean', 'Std', 'Var', 'Entropy','Max', 'Min', 'AbsMean', 'Kurtosis', 'RMS', 'CrestFactor','Skewness', 'ClearanceFactor', 'ShapeFactor']
# logical_configs:
  # channel_1:
  #   features: ['$Mean$', '$Std$']
  # channel_2:
  #   features: ['$Mean$', '$Std$']
args:

  device: cuda
# data
  task: 'task1' # task1:basic |  | task2:/ noise | task3 : generalization | task4: few-shot
  data_dir: '/home/user/data/a_bearing/a_006_THU_pro/LQ_fusion/1hz'
  # data_dir: '/home/user/data/a_bearing/a_006_THU_pro/LQ_fusion/10hz'
  # data_dir: '/home/user/data/a_bearing/a_006_THU_pro/LQ_fusion/15hz'
  # data_dir: '/home/user/data/a_bearing/a_018_THU24_pro/IF'


# model
  model: TSPM
  skip_connection: true
  num_classes: 4
  in_dim : 4096
  out_dim : 4096
  in_channels : 2
  out_channels : 3
  scale : 4

  f_c_mu: 0
  f_c_sigma: 0.1
  f_b_mu: 0
  f_b_sigma: 0.1

# hyperparameter
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 100
  weight_decay: 0.0001
  num_workers: 32
  seed: 17

# train
  monitor: 'val_loss'
  patience: 8
  gpus: 8
  weight_decay: 0.0001
  l1_norm: 0.01
